// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwZSDQCpFetcuMkzJbWEoQSbCx0IBH1SQ',
    appId: '1:424591312586:web:8784b3a9f314a4597f9633',
    messagingSenderId: '424591312586',
    projectId: 'spor-eb411',
    authDomain: 'spor-eb411.firebaseapp.com',
    storageBucket: 'spor-eb411.appspot.com',
    measurementId: 'G-WZPE750B5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcmQsaUDounAZB11I_Vjj5gOBzkepUZ1g',
    appId: '1:424591312586:android:e87ea08156908fb07f9633',
    messagingSenderId: '424591312586',
    projectId: 'spor-eb411',
    storageBucket: 'spor-eb411.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5sWXrMB52D-nOdvY-NIFwjynm3vBwnvA',
    appId: '1:424591312586:ios:73e241f3d0535b357f9633',
    messagingSenderId: '424591312586',
    projectId: 'spor-eb411',
    storageBucket: 'spor-eb411.appspot.com',
    iosBundleId: 'com.example.spor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5sWXrMB52D-nOdvY-NIFwjynm3vBwnvA',
    appId: '1:424591312586:ios:78f0427f999504d37f9633',
    messagingSenderId: '424591312586',
    projectId: 'spor-eb411',
    storageBucket: 'spor-eb411.appspot.com',
    iosBundleId: 'com.example.spor.RunnerTests',
  );
}
